CREATE TABLE currencies
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(3)                              NOT NULL,
    unit       INTEGER                                 NOT NULL,
    rate       DECIMAL(12, 6),
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_currencies PRIMARY KEY (id)
);

ALTER TABLE currencies
    ADD CONSTRAINT uc_currency_name UNIQUE (name);

CREATE INDEX idx_currencies_name ON currencies (name);

CREATE INDEX idx_currencies_unit ON currencies (unit);