CREATE TABLE tax_groups
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(7)                              NOT NULL,
    value INTEGER                                 NOT NULL,
    CONSTRAINT pk_tax_groups PRIMARY KEY (id)
);

ALTER TABLE tax_groups
    ADD CONSTRAINT uc_tax_group_name UNIQUE (name);

CREATE INDEX inx_tax_groups_name ON tax_groups (name);

CREATE INDEX inx_tax_groups_value ON tax_groups (value);