CREATE TABLE product_tax_groups
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(7)                              NOT NULL,
    value INTEGER                                 NOT NULL,
    CONSTRAINT pk_product_tax_groups PRIMARY KEY (id)
);

ALTER TABLE product_tax_groups
    ADD CONSTRAINT uc_product_tax_group_name UNIQUE (name);

CREATE INDEX inx_product_tax_groups_name ON product_tax_groups (name);

CREATE INDEX inx_product_tax_groups_value ON product_tax_groups (value);