CREATE TABLE product_barcodes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    barcode    VARCHAR(128)                            NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_barcodes PRIMARY KEY (id)
);

ALTER TABLE product_barcodes
    ADD CONSTRAINT uc_product_barcode_barcode_product UNIQUE (barcode, product_id);

CREATE INDEX inx_product_barcodes_barcode ON product_barcodes (barcode);

ALTER TABLE product_barcodes
    ADD CONSTRAINT FK_PRODUCT_BARCODES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

CREATE INDEX inx_product_barcodes_product_id ON product_barcodes (product_id);