CREATE TABLE product_identifiers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type       SMALLINT                                NOT NULL,
    value      VARCHAR(50)                             NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_identifiers PRIMARY KEY (id)
);

ALTER TABLE product_identifiers
    ADD CONSTRAINT uc_product_identifier_type_product_id UNIQUE (type, product_id);

CREATE INDEX inx_product_identifiers_type_value ON product_identifiers (type, value);

CREATE INDEX inx_product_identifiers_value ON product_identifiers (value);

ALTER TABLE product_identifiers
    ADD CONSTRAINT FK_PRODUCT_IDENTIFIERS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

CREATE INDEX inx_product_identifiers_product_id ON product_identifiers (product_id);