CREATE TABLE product_prices
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type       SMALLINT                                NOT NULL,
    price      DECIMAL(15, 8),
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_prices PRIMARY KEY (id)
);

ALTER TABLE product_prices
    ADD CONSTRAINT uc_product_price_type_product UNIQUE (type, product_id);

CREATE INDEX idx_product_prices_type_product_id ON product_prices (type, product_id);

ALTER TABLE product_prices
    ADD CONSTRAINT FK_PRODUCT_PRICES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

CREATE INDEX idx_product_prices_product_id ON product_prices (product_id);