CREATE TABLE product_locations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    zone       VARCHAR(10)                             NOT NULL,
    series     INTEGER                                 NOT NULL,
    shelf      VARCHAR(10)                             NOT NULL,
    level      INTEGER                                 NOT NULL,
    position   INTEGER                                 NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_locations PRIMARY KEY (id)
);

ALTER TABLE product_locations
    ADD CONSTRAINT uc_product_location_zone_series_shelf_level_position UNIQUE (zone, series, shelf, level, position);

CREATE INDEX inx_product_locations_zone ON product_locations (zone);

CREATE INDEX inx_product_locations_zone_series ON product_locations (zone, series);

CREATE INDEX inx_product_locations_zone_series_shelf ON product_locations (zone, series, shelf);

ALTER TABLE product_locations
    ADD CONSTRAINT FK_PRODUCT_LOCATIONS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

CREATE INDEX inx_product_locations_product_id ON product_locations (product_id);