CREATE TABLE product_lots
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lot            VARCHAR(50)                             NOT NULL,
    date_of_issue  TIMESTAMP WITHOUT TIME ZONE,
    date_of_expiry TIMESTAMP WITHOUT TIME ZONE,
    location_id    BIGINT                                  NOT NULL,
    product_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_lots PRIMARY KEY (id)
);

ALTER TABLE product_lots
    ADD CONSTRAINT uq_product_lots_product_id_lot UNIQUE (product_id, lot);

CREATE INDEX inx_product_lots_date_of_expiry ON product_lots (date_of_expiry);

CREATE INDEX inx_product_lots_lot ON product_lots (lot);

ALTER TABLE product_lots
    ADD CONSTRAINT FK_PRODUCT_LOTS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES product_locations (id);

ALTER TABLE product_lots
    ADD CONSTRAINT FK_PRODUCT_LOTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

CREATE INDEX inx_product_lots_product_id ON product_lots (product_id);