CREATE TABLE objects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(10),
    name       VARCHAR(100)                            NOT NULL,
    price_type SMALLINT                                NOT NULL,
    is_active  BOOLEAN                                 NOT NULL,
    address    VARCHAR(255),
    city_id    BIGINT,
    CONSTRAINT pk_objects PRIMARY KEY (id)
);

ALTER TABLE objects
    ADD CONSTRAINT uc_object_name UNIQUE (name);

CREATE INDEX idx_objects_code_active ON objects (code, is_active);

CREATE INDEX idx_objects_name_active ON objects (name, is_active);

ALTER TABLE objects
    ADD CONSTRAINT FK_OBJECTS_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

CREATE INDEX idx_objects_city_id ON objects (city_id);