CREATE TABLE countries
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(48)                             NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

ALTER TABLE countries
    ADD CONSTRAINT uc_countries_name UNIQUE (name);

CREATE INDEX inx_countries_name ON countries (name);