CREATE TABLE vendors
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    picture_url   VARCHAR(2048),
    display_order BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_vendors PRIMARY KEY (id)
);

ALTER TABLE vendors
    ADD CONSTRAINT uc_vendor_name UNIQUE (name);

CREATE INDEX inx_vendor_name ON vendors (name);

CREATE INDEX inx_vendors_display_order ON vendors (display_order);