CREATE TABLE city_regions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(30)                             NOT NULL,
    country_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_city_regions PRIMARY KEY (id)
);

ALTER TABLE city_regions
    ADD CONSTRAINT uc_city_region_name_country UNIQUE (name, country_id);

CREATE INDEX inx_city_regions_name ON city_regions (name);

ALTER TABLE city_regions
    ADD CONSTRAINT FK_CITY_REGIONS_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);

CREATE INDEX inx_city_regions_country_id ON city_regions (country_id);