CREATE TABLE cities
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    postal_code    VARCHAR(12)                             NOT NULL,
    name           VARCHAR(30)                             NOT NULL,
    city_region_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

CREATE INDEX inx_cities_name ON cities (name);

CREATE INDEX inx_cities_postal_code ON cities (postal_code);

CREATE INDEX inx_cities_postal_code_name ON cities (postal_code, name);

ALTER TABLE cities
    ADD CONSTRAINT FK_CITIES_ON_CITY_REGION FOREIGN KEY (city_region_id) REFERENCES city_regions (id);

CREATE INDEX inx_cities_city_region_id ON cities (city_region_id);