CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type          SMALLINT                                NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    display_order BIGINT                                  NOT NULL,
    parent_id     BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_category_name_parent_type UNIQUE (name, parent_id, type);

CREATE INDEX idx_categories_display_order ON categories (display_order, type);

CREATE INDEX idx_categories_name ON categories (name, type);

CREATE INDEX idx_categories_parent_id ON categories (parent_id, type);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES categories (id);