CREATE TABLE partners
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku                 VARCHAR(50),
    company_name        VARCHAR(200)                            NOT NULL,
    contact_person_name VARCHAR(100),
    tax_number          VARCHAR(18)                             NOT NULL,
    vat_number          VARCHAR(20),
    partner_type        VARCHAR(9)                              NOT NULL,
    is_active           BOOLEAN                                 NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_partners PRIMARY KEY (id)
);

ALTER TABLE partners
    ADD CONSTRAINT uc_partner_company_name UNIQUE (company_name);

ALTER TABLE partners
    ADD CONSTRAINT uc_partner_tax_number UNIQUE (tax_number);

CREATE INDEX idx_partners_company_name_active ON partners (company_name, is_active);

CREATE INDEX idx_partners_is_active ON partners (is_active);

CREATE INDEX idx_partners_sku_active ON partners (sku, is_active);

CREATE INDEX idx_partners_tax_number_active ON partners (tax_number, is_active);

CREATE INDEX idx_partners_vat_number_active ON partners (vat_number, is_active);