CREATE TABLE partner_addresses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    is_default BOOLEAN                                 NOT NULL,
    city_id    BIGINT                                  NOT NULL,
    partner_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_partner_addresses PRIMARY KEY (id)
);

CREATE INDEX inx_partner_addresses_partner_id_is_default ON partner_addresses (partner_id, is_default);

ALTER TABLE partner_addresses
    ADD CONSTRAINT FK_PARTNER_ADDRESSES_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

ALTER TABLE partner_addresses
    ADD CONSTRAINT FK_PARTNER_ADDRESSES_ON_PARTNER FOREIGN KEY (partner_id) REFERENCES partners (id);

CREATE INDEX inx_partner_addresses_partner_id ON partner_addresses (partner_id);