CREATE TABLE partner_bank_accounts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(150)                            NOT NULL,
    iban       VARCHAR(34)                             NOT NULL,
    swift      VARCHAR(11)                             NOT NULL,
    is_default BOOLEAN                                 NOT NULL,
    partner_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_partner_bank_accounts PRIMARY KEY (id)
);

CREATE INDEX inx_partner_bank_accounts_partner_id_is_default ON partner_bank_accounts (partner_id, is_default);

ALTER TABLE partner_bank_accounts
    ADD CONSTRAINT FK_PARTNER_BANK_ACCOUNTS_ON_PARTNER FOREIGN KEY (partner_id) REFERENCES partners (id);

CREATE INDEX inx_partner_bank_accounts_partner_id ON partner_bank_accounts (partner_id);