CREATE TABLE partner_additional_infos
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(254),
    phone_number VARCHAR(20),
    partner_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_partner_additional_infos PRIMARY KEY (id)
);

ALTER TABLE partner_additional_infos
    ADD CONSTRAINT FK_PARTNER_ADDITIONAL_INFOS_ON_PARTNER FOREIGN KEY (partner_id) REFERENCES partners (id);

CREATE INDEX inx_partner_additional_infos_partner_id ON partner_additional_infos (partner_id);