CREATE TABLE products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version    BIGINT,
    sku        VARCHAR(50)                             NOT NULL,
    name       VARCHAR(300)                            NOT NULL,
    is_active  BOOLEAN                                 NOT NULL,
    type       SMALLINT                                NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE products
    ADD CONSTRAINT uc_product_sku UNIQUE (sku);

CREATE INDEX idx_products_is_active ON products (is_active);

CREATE INDEX idx_products_name_active ON products (name, is_active);

CREATE INDEX idx_products_sku_active ON products (sku, is_active);

CREATE INDEX idx_products_type_active ON products (type, is_active);