CREATE TABLE suppliers
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                VARCHAR(10),
    company_name        VARCHAR(200)                            NOT NULL,
    contact_person_name VARCHAR(100),
    email               VARCHAR(254),
    phone_number        VARCHAR(20),
    country             VARCHAR(48),
    city                VARCHAR(168),
    address             VARCHAR(255),
    postal_code         VARCHAR(12),
    tax_number          VARCHAR(20),
    vat_number          VARCHAR(20),
    bank_name           VARCHAR(150),
    bank_iban           VARCHAR(34),
    bank_swift          VARCHAR(11),
    active              BOOLEAN                                 NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_suppliers PRIMARY KEY (id)
);

ALTER TABLE suppliers
    ADD CONSTRAINT uc_suppliers_code UNIQUE (code);

ALTER TABLE suppliers
    ADD CONSTRAINT uc_suppliers_company_name UNIQUE (company_name);